name: Docker
on: workflow_call
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: build
        run: |
          echo build $GITHUB_REPOSITORY $GITHUB_REF_TYPE $GITHUB_REF_NAME
          
          repo_dir="repo_$(printf %s "$GITHUB_REPOSITORY" | tr -c A-Za-z0-9_- _)"
          [ -e "$repo_dir" ] && [ ! -d "$repo_dir/.git" ] && rm -rf "$repo_dir"
          [ ! -e "$repo_dir" ] && git init --quiet "$repo_dir"
          git -C "$repo_dir" fetch --depth=1 --force --quiet \
            "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git" \
            "$GITHUB_REF:$GITHUB_REF"
          git -C "$repo_dir" checkout --detach --quiet "$GITHUB_REF"

          /opt/github-runner/docker-login.sh
          
          if [ "$GITHUB_REF_TYPE" = branch ] && echo "$GITHUB_REF_NAME" | grep -q "^[0-9]\+\.[0-9]\+\.x$"
          then
            source /opt/github-runner/env
          
            image1="$my_registry/$GITHUB_REPOSITORY:$GITHUB_REF_NAME"
            image2="$my_registry/$GITHUB_REPOSITORY:test"
            docker build --pull --tag="$image1" --tag="$image2" "$repo_dir"
          
            /opt/github-runner/create-repository.sh "$GITHUB_REPOSITORY"
          
            docker push "$image1"
            docker push "$image2"
          elif [ "$GITHUB_REF_TYPE" = tag ] && echo "$GITHUB_REF_NAME" | grep -q "^[0-9]\+\.[0-9]\+\.[0-9]\+$"
          then
            source /opt/github-runner/env
            
            cache_tag=$(echo "$GITHUB_REF_NAME" | sed 's/^\([0-9]\+\.[0-9]\+\)\.[0-9]\+$/\1.x/')
            cache_image="$my_registry/$GITHUB_REPOSITORY:$cache_tag"
            image="$my_registry/$GITHUB_REPOSITORY:$GITHUB_REF_NAME"
            
            /opt/github-runner/create-repository.sh "$GITHUB_REPOSITORY"
          
            docker build --cache-from="$cache_image" --tag="$image" "$repo_dir"
          
            docker push "$image"
          else
            docker build "$repo_dir"
          fi
